name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]
          rust-toolchain: [stable]
          arch: [x86_64, aarch64]

    steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
       target: aarch64-apple-darwin
       toolchain: ${{matrix.rust-toolchain}}
       components: rustfmt
      
    - name: Check out code 
      uses: actions/checkout@v3
    
    - name: Build and test
      run: |
        uname -a
        uname -s
        arch
        rustup default aarch64-apple-darwin
        cargo fmt -- --check
        cargo build --verbose
        cargo test --verbose
        
